version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - AUTH_URL=${AUTH_URL}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
